# Lynx loader — calls lx binary, evals the generated shell glue.
# Intentionally thin. Logic lives in Rust.

_lynx_bin="${HOME}/.local/bin/lx"

if [[ ! -x "$_lynx_bin" ]]; then
  print -u2 "Lynx: 'lx' binary not found at $_lynx_bin. Run the installer."
  return 1
fi

# Detect context automatically
if [[ -n "${CLAUDE_CODE}" || -n "${CURSOR_SESSION}" ]]; then
  _lynx_context="agent"
else
  _lynx_context="${LYNX_CONTEXT:-interactive}"
fi

# Eval the shell glue generated by lx
eval "$("$_lynx_bin" init --context "$_lynx_context")"
