//! Auto-plugin generation for installed tools.
//!
//! When a tool is installed via `lx install`, this module generates a
//! Lynx plugin that aliases the system command (e.g. `ls` → `eza --icons`).
//! The generated plugin follows the standard plugin protocol: plugin.toml,
//! shell/init.zsh, shell/aliases.zsh.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use lynx_core::env_vars;

use crate::schema::RegistryEntry;

/// Smart default flags for known tools — applied when aliasing.
fn smart_defaults(tool: &str) -> Option<&'static str> {
    match tool {
        "eza" => Some("--icons --color=auto --group-directories-first"),
        "bat" => Some("--style=auto --paging=never"),
        "fd" => Some("--color=auto"),
        "dust" => Some("--reverse"),
        "procs" => Some("--color=auto"),
        _ => None,
    }
}

/// Generate a complete Lynx plugin for an installed tool.
///
/// Creates the plugin directory at `plugins_dir/<name>/` with:
/// - plugin.toml (manifest with binary dep and context-gated aliases)
/// - shell/init.zsh
/// - shell/aliases.zsh
///
/// Returns the path to the generated plugin directory.
pub fn generate_tool_plugin(entry: &RegistryEntry, plugins_dir: &Path) -> Result<PathBuf> {
    let name = &entry.name;
    let plugin_dir = plugins_dir.join(name);
    let shell_dir = plugin_dir.join("shell");

    std::fs::create_dir_all(&shell_dir)
        .with_context(|| format!("failed to create plugin dir {}", shell_dir.display()))?;

    // Generate plugin.toml
    let replaces = entry.replaces.as_deref().unwrap_or("");
    let aliases_list = if replaces.is_empty() {
        String::new()
    } else {
        format!("[\"{replaces}\"]")
    };

    let manifest = format!(
        r#"[plugin]
name        = "{name}"
version     = "0.1.0"
description = "Auto-generated plugin for {name} — installed via lx install"
authors     = ["lynx-sh"]

[load]
lazy  = false
hooks = []

[deps]
binaries = ["{name}"]
plugins  = []

[exports]
functions = []
aliases   = {aliases_list}

[contexts]
disabled_in = ["agent", "minimal"]
"#
    );
    std::fs::write(plugin_dir.join("plugin.toml"), &manifest)
        .context("failed to write plugin.toml")?;

    // Generate shell/aliases.zsh
    let aliases_content = if !replaces.is_empty() {
        let flags = smart_defaults(name).unwrap_or("");
        if flags.is_empty() {
            format!("alias {replaces}='{name}'\n")
        } else {
            format!("alias {replaces}='{name} {flags}'\n")
        }
    } else {
        String::from("# No alias — this tool does not replace a system command.\n")
    };
    std::fs::write(shell_dir.join("aliases.zsh"), &aliases_content)
        .context("failed to write aliases.zsh")?;

    // Generate shell/init.zsh
    let init = format!(
        r#"# {name} plugin — auto-generated by lx install
# Context gate is enforced by lx plugin exec (Rust). No logic here.

[[ "${{{context_var}}}" != "agent" && "${{{context_var}}}" != "minimal" ]] && \
  source "${{{plugin_dir_var}}}/{name}/shell/aliases.zsh"
"#,
        context_var = env_vars::LYNX_CONTEXT,
        plugin_dir_var = env_vars::LYNX_PLUGIN_DIR,
    );
    std::fs::write(shell_dir.join("init.zsh"), &init).context("failed to write init.zsh")?;

    Ok(plugin_dir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::{InstallMethods, PackageType, PluginVersion, RegistryEntry};

    fn tool_entry(name: &str, replaces: Option<&str>) -> RegistryEntry {
        RegistryEntry {
            name: name.into(),
            description: format!("{name} tool"),
            package_type: PackageType::Tool,
            replaces: replaces.map(|s| s.into()),
            install: Some(InstallMethods {
                brew: Some(name.into()),
                ..Default::default()
            }),
            latest_version: "1.0.0".into(),
            versions: vec![PluginVersion {
                version: "1.0.0".into(),
                url: "x".into(),
                checksum_sha256: "x".into(),
                min_lynx_version: None,
            }],
            ..Default::default()
        }
    }

    #[test]
    fn generates_valid_plugin_structure() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("eza", Some("ls"));
        let path = generate_tool_plugin(&entry, dir.path()).unwrap();

        assert!(path.join("plugin.toml").exists());
        assert!(path.join("shell/init.zsh").exists());
        assert!(path.join("shell/aliases.zsh").exists());
    }

    #[test]
    fn manifest_has_correct_fields() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("eza", Some("ls"));
        generate_tool_plugin(&entry, dir.path()).unwrap();

        let manifest = std::fs::read_to_string(dir.path().join("eza/plugin.toml")).unwrap();
        assert!(manifest.contains("name        = \"eza\""));
        assert!(manifest.contains("binaries = [\"eza\"]"));
        assert!(manifest.contains("aliases   = [\"ls\"]"));
        assert!(manifest.contains("disabled_in = [\"agent\", \"minimal\"]"));
    }

    #[test]
    fn aliases_use_smart_defaults_for_eza() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("eza", Some("ls"));
        generate_tool_plugin(&entry, dir.path()).unwrap();

        let aliases = std::fs::read_to_string(dir.path().join("eza/shell/aliases.zsh")).unwrap();
        assert!(
            aliases.contains("--icons"),
            "expected --icons in: {aliases}"
        );
        assert!(
            aliases.contains("--color=auto"),
            "expected --color=auto in: {aliases}"
        );
    }

    #[test]
    fn aliases_use_smart_defaults_for_bat() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("bat", Some("cat"));
        generate_tool_plugin(&entry, dir.path()).unwrap();

        let aliases = std::fs::read_to_string(dir.path().join("bat/shell/aliases.zsh")).unwrap();
        assert!(
            aliases.contains("--style=auto"),
            "expected --style=auto in: {aliases}"
        );
    }

    #[test]
    fn no_alias_when_replaces_is_none() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("ripgrep", None);
        generate_tool_plugin(&entry, dir.path()).unwrap();

        let aliases =
            std::fs::read_to_string(dir.path().join("ripgrep/shell/aliases.zsh")).unwrap();
        assert!(
            aliases.contains("No alias"),
            "expected no alias comment in: {aliases}"
        );

        let manifest = std::fs::read_to_string(dir.path().join("ripgrep/plugin.toml")).unwrap();
        assert!(
            manifest.contains("aliases   = "),
            "aliases list should be empty"
        );
    }

    #[test]
    fn simple_alias_for_unknown_tool() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("zoxide", Some("cd"));
        generate_tool_plugin(&entry, dir.path()).unwrap();

        let aliases = std::fs::read_to_string(dir.path().join("zoxide/shell/aliases.zsh")).unwrap();
        assert_eq!(aliases.trim(), "alias cd='zoxide'");
    }

    #[test]
    fn init_zsh_has_context_gate() {
        let dir = tempfile::tempdir().unwrap();
        let entry = tool_entry("eza", Some("ls"));
        generate_tool_plugin(&entry, dir.path()).unwrap();

        let init = std::fs::read_to_string(dir.path().join("eza/shell/init.zsh")).unwrap();
        assert!(
            init.contains(env_vars::LYNX_CONTEXT),
            "expected context gate in init.zsh"
        );
        assert!(init.contains("agent"), "expected agent context check");
    }
}
