#!/usr/bin/env bats
# Integration tests for lx init and shell integration layer
# Each test runs in an isolated temp HOME directory

setup() {
  export HOME="$(mktemp -d)"
  export LYNX_TEST=1
}

teardown() {
  rm -rf "$HOME"
}

@test "lx init produces valid zsh output" {
  run lx init --context interactive
  [ "$status" -eq 0 ]
  echo "$output" | zsh -n   # syntax check
}

@test "lx init sets LYNX_CONTEXT in output" {
  run lx init --context agent
  [ "$status" -eq 0 ]
  [[ "$output" == *"LYNX_CONTEXT=agent"* ]]
}

@test "lx init does not auto-start daemon (daemon is opt-in)" {
  run lx init --context interactive
  [ "$status" -eq 0 ]
  # Must not invoke lx daemon directly — bare wrapper definitions are allowed,
  # but calling lx daemon start/stop/status at init time is forbidden (D-012).
  [[ "$output" != *"lx daemon start"* ]]
  [[ "$output" != *"lx daemon stop"* ]]
  [[ "$output" != *"lx daemon status"* ]]
}

@test "agent context detected from CLAUDE_CODE env var" {
  CLAUDE_CODE=1 run lx init
  [ "$status" -eq 0 ]
  [[ "$output" == *"LYNX_CONTEXT=agent"* ]]
}

@test "shell protocol line limits are enforced" {
  local loader="$BATS_TEST_DIRNAME/../../../shell/core/loader.zsh"
  local hooks="$BATS_TEST_DIRNAME/../../../shell/core/hooks.zsh"
  local bridge="$BATS_TEST_DIRNAME/../../../shell/lib/eval-bridge.zsh"
  local atuin="$BATS_TEST_DIRNAME/../../../plugins/atuin/shell/init.zsh"

  [ "$(wc -l < "$loader" | tr -d ' ')" -le 60 ]
  [ "$(wc -l < "$hooks" | tr -d ' ')" -le 60 ]
  [ "$(wc -l < "$bridge" | tr -d ' ')" -le 60 ]
  [ "$(wc -l < "$atuin" | tr -d ' ')" -le 10 ]
}

@test "thin shell files have no branching keywords" {
  local loader="$BATS_TEST_DIRNAME/../../../shell/core/loader.zsh"
  local atuin="$BATS_TEST_DIRNAME/../../../plugins/atuin/shell/init.zsh"
  local pattern='(^|[[:space:]])(if|for|while|case)([[:space:]]|$)'

  # eval-bridge.zsh is excluded: it has a documented D-001 exception for the
  # eval stderr trap (see shell-protocol.md). The trap is I/O plumbing only —
  # all error formatting is delegated to `lx shell-error` (Rust/LynxError::Shell).
  run rg -n "$pattern" "$loader" "$atuin"
  [ "$status" -eq 1 ]
}

# ── Guardrail: shell protocol violations ──────────────────────────────────────

@test "guardrail: all plugin shell/init.zsh files are within 10-line limit" {
  local plugins_dir="$BATS_TEST_DIRNAME/../../../plugins"
  local violations=()
  while IFS= read -r -d '' f; do
    local count
    count=$(wc -l < "$f" | tr -d ' ')
    [ "$count" -le 10 ] || violations+=("$f ($count lines)")
  done < <(find "$plugins_dir" -name "init.zsh" -print0)
  [ "${#violations[@]}" -eq 0 ]
}

@test "guardrail: no branching keywords in any plugin shell/init.zsh" {
  local plugins_dir="$BATS_TEST_DIRNAME/../../../plugins"
  local pattern='(^|[[:space:]])(if|for|while|case)([[:space:]]|$)'
  # Collect all plugin init.zsh paths into an array
  local files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$plugins_dir" -name "init.zsh" -print0)
  [ "${#files[@]}" -gt 0 ]
  run rg -n "$pattern" "${files[@]}"
  [ "$status" -eq 1 ]
}

@test "guardrail: lx init output does not embed raw shell logic (no if/for/while)" {
  run lx init --context interactive
  [ "$status" -eq 0 ]
  # Daemon check snippet uses if — that is the one permitted pattern in eval output
  # (it's generated by Rust, not a shell file). We only ban it in static shell files above.
  # This test verifies the output is valid zsh and exits 0 — structural check.
  echo "$output" | zsh -n
}
